# Generated by Django 4.2 on 2024-09-09 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=10000)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('PartTime', 'PartTime'), ('FullTime', 'FullTime'), ('Contract', 'Contract')], max_length=50)),
                ('education', models.CharField(choices=[('PHD', 'PHD'), ('Master', 'Master'), ('Bachelor', 'Bachelor')], max_length=50)),
                ('experience', models.CharField(choices=[('NoExperience', 'NoExperience'), ('Junior', 'Junior'), ('MidLevel', 'MidLevel'), ('Senior', 'Senior')], max_length=50)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('resume', models.FileField(upload_to='resume')),
                ('cover_letter', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_apply', to='job.job')),
            ],
        ),
    ]
